// docker-compose-manager-front/src/components/compose/ProjectStatsCard.tsx
import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { containersApi } from '@/api/containers';
import { EntityState, type ComposeService, type ContainerStats } from '@/types';
import { Activity, Cpu, HardDrive } from 'lucide-react';
import { ResourceStatsCard, type StatsMetricConfig } from '@/components/common/ResourceStatsCard';
import { t } from '@/i18n';

interface ProjectStatsCardProps {
  services: ComposeService[];
}

interface AggregatedStats {
  cpuPercentage: number;
  memoryUsage: number;
  memoryLimit: number;
  memoryPercentage: number;
  networkRx: number;
  networkTx: number;
  diskRead: number;
  diskWrite: number;
  timestamp: Date;
}

export function ProjectStatsCard({ services }: ProjectStatsCardProps) {
  const [statsHistory, setStatsHistory] = useState<AggregatedStats[]>([]);
  const [currentStats, setCurrentStats] = useState<AggregatedStats | null>(null);

  // Fetch stats for all services every 1 seconds
  const { data: servicesStats } = useQuery({
    queryKey: ['projectStats', services.map(s => s.id).sort().join(',')],
    queryFn: async () => {
      const statsPromises = services
        .filter(s => s.state === EntityState.Running)
        .map(async (service) => {
          try {
            return await containersApi.getStats(service.id);
          } catch (error: unknown) {
            // Don't log 404 errors - container was probably stopped/removed
            const axiosError = error as { response?: { status?: number } };
            if (axiosError?.response?.status !== 404) {
              console.error(`Failed to fetch stats for ${service.name}:`, error);
            }
            return null;
          }
        });

      const stats = await Promise.all(statsPromises);
      return stats.filter((s): s is ContainerStats => s !== null);
    },
    refetchInterval: 1000, // Refresh every 1 seconds
    enabled: services.some(s => s.state === EntityState.Running),
    retry: false, // Don't retry on failure - if container is gone, it's gone
  });

  // Update current stats when new data arrives
  useEffect(() => {
    if (!servicesStats || servicesStats.length === 0) return;

    const aggregated: AggregatedStats = {
      cpuPercentage: 0,
      memoryUsage: 0,
      memoryLimit: 0,
      memoryPercentage: 0,
      networkRx: 0,
      networkTx: 0,
      diskRead: 0,
      diskWrite: 0,
      timestamp: new Date(),
    };

    servicesStats.forEach((stats) => {
      aggregated.cpuPercentage += stats.cpuPercentage;
      aggregated.memoryUsage += stats.memoryUsage;
      aggregated.memoryLimit += stats.memoryLimit;
      aggregated.networkRx += stats.networkRx;
      aggregated.networkTx += stats.networkTx;
      aggregated.diskRead += stats.diskRead;
      aggregated.diskWrite += stats.diskWrite;
    });

    // Calculate average memory percentage
    if (aggregated.memoryLimit > 0) {
      aggregated.memoryPercentage = (aggregated.memoryUsage / aggregated.memoryLimit) * 100;
    }

    setCurrentStats(aggregated);
  }, [servicesStats]);

  // Timer to add data points every 2 seconds (keeps chart moving even if values don't change)
  useEffect(() => {
    if (!currentStats) return;

    const interval = setInterval(() => {
      // Add a new point with current stats and current timestamp
      const newPoint: AggregatedStats = {
        ...currentStats,
        timestamp: new Date(), // Always use current time to keep chart moving
      };

      setStatsHistory((prev) => {
        // Keep only last 5 minutes of data (sliding window)
        const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);
        const filtered = prev.filter(stat => stat.timestamp >= fiveMinutesAgo);
        return [...filtered, newPoint];
      });
    }, 1000); // Add point every 2 seconds

    return () => clearInterval(interval);
  }, [currentStats]);

  // (Removed unused formatBytes helper after refactor)


  // Determine best unit for memory based on max value in dataset
  const getBestMemoryUnit = (data: AggregatedStats[]): { unit: string; divisor: number } => {
    if (data.length === 0) return { unit: 'MB', divisor: 1024 * 1024 };

    const maxValue = Math.max(...data.map(d => d.memoryUsage));
    const k = 1024;

    if (maxValue >= k * k * k) {
      return { unit: 'GB', divisor: k * k * k };
    } else if (maxValue >= k * k) {
      return { unit: 'MB', divisor: k * k };
    } else if (maxValue >= k) {
      return { unit: 'KB', divisor: k };
    }
    return { unit: 'B', divisor: 1 };
  };

  // Get adaptive memory unit for current data (network handled by grouped card)
  const memoryUnit = getBestMemoryUnit(statsHistory);

  const isActive = services.some(s => s.state === EntityState.Running);
  if (!isActive) {
    return (
      <div className="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg p-6">
        <div className="flex items-center gap-2 mb-4">
          <Activity className="h-5 w-5 text-gray-600 dark:text-gray-400" />
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{t('common.projectStatistics')}</h3>
        </div>
        <p className="text-sm text-gray-600 dark:text-gray-400">{t('common.noRunningServices')}</p>
      </div>
    );
  }

  const metrics: StatsMetricConfig<AggregatedStats>[] = [
    {
      id: 'cpuPercentage',
      label: 'CPU Usage',
      icon: <Cpu className="h-4 w-4 text-blue-600 dark:text-blue-400" />,
      value: s => s.cpuPercentage,
      format: v => v.toFixed(2) + '%',
      unit: '%',
      color: '#3b82f6',
    },
    {
      id: 'memoryUsage',
      label: 'Memory',
      icon: <HardDrive className="h-4 w-4 text-green-600 dark:text-green-400" />,
      value: s => s.memoryUsage / memoryUnit.divisor,
      headerFormat: (stats) => `${(stats.memoryUsage / memoryUnit.divisor).toFixed(2)} ${memoryUnit.unit} / ${(stats.memoryLimit / memoryUnit.divisor).toFixed(2)} ${memoryUnit.unit}`,
      unit: memoryUnit.unit,
      color: '#10b981',
    },
  ];

  // Grouped network chart (RX/TX raw bytes for adaptive scaling inside ResourceStatsCard)
  const groups = [
    {
      id: 'network',
      label: 'Network (RX / TX)',
      metrics: [
        { id: 'networkRx', label: 'RX', value: (s: AggregatedStats) => s.networkRx, color: '#8b5cf6' },
        { id: 'networkTx', label: 'TX', value: (s: AggregatedStats) => s.networkTx, color: '#f59e0b' },
      ],
    },
    {
			id: 'diskio',
			label: 'Disk IO (Read / Write)',
			metrics: [
				{ id: 'diskRead', label: 'Read', value: (s: AggregatedStats) => s.diskRead, color: '#8b5cf6' },
				{ id: 'diskWrite', label: 'Write', value: (s: AggregatedStats) => s.diskWrite, color: '#ec4899' },
			],
		},
  ];

  return (
    <ResourceStatsCard
      title="Project Statistics"
      isActive={isActive}
      getStats={async () => currentStats}
      metrics={metrics}
      groups={groups}
      fetchIntervalMs={1000}
      chartIntervalMs={1000}
      maxWindowMinutes={5}
      emptyMessage="No running services to display stats."
    />
  );
}

// docker-compose-manager-front/src/lib/components/compose/ProjectStatsCard.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { createQuery } from '@tanstack/svelte-query';
	import { containersApi } from '$lib/api';
	import { Activity, Cpu, HardDrive } from 'lucide-svelte';
	import { t } from '$lib/i18n';
	import LineChart from '$lib/components/charts/LineChart.svelte';
	import type { ComposeService, ContainerStats } from '$lib/types';
	import { formatBytes, getBestMemoryUnit, getBestNetworkUnit, getBestNetworkRateUnit, getBestDiskUnit, getBestDiskRateUnit } from '$lib/utils/units';

	interface Props {
		services: ComposeService[];
	}

	let { services }: Props = $props();

	interface AggregatedStats {
		cpuPercentage: number;
		memoryUsage: number;
		memoryLimit: number;
		memoryPercentage: number;
		networkRx: number;
		networkTx: number;
		diskRead: number;
		diskWrite: number;
		timestamp: Date;
	}

	interface RateStats {
		networkRxRate: number;
		networkTxRate: number;
		diskReadRate: number;
		diskWriteRate: number;
		timestamp: Date;
	}

	let statsHistory = $state<AggregatedStats[]>([]);
	let rateHistory = $state<RateStats[]>([]);
	let currentStats = $state<AggregatedStats | null>(null);
	let currentRates = $state<RateStats | null>(null);
	// Use plain variables (not reactive) to avoid circular dependency in effects
	let previousStatsRef: AggregatedStats | null = null;

	const isActive = $derived(services.some((s) => s.state === 'Running'));
	const runningServiceIds = $derived(services.filter((s) => s.state === 'Running').map((s) => s.id));

	// Fetch stats for all running services every 1 second
	const servicesStatsQuery = createQuery(() => ({
		queryKey: ['projectStats', runningServiceIds.sort().join(',')],
		queryFn: async () => {
			const statsPromises = runningServiceIds.map(async (serviceId) => {
				try {
					return await containersApi.getStats(serviceId);
				} catch (error: any) {
					// Don't log 404 errors - container was probably stopped/removed
					if (error?.response?.status !== 404) {
						console.error(`Failed to fetch stats for service ${serviceId}:`, error);
					}
					return null;
				}
			});

			const stats = await Promise.all(statsPromises);
			return stats.filter((s): s is ContainerStats => s !== null);
		},
		refetchInterval: 1000,
		enabled: isActive,
		retry: false
	}));

	// Update current stats and history when new data arrives
	$effect(() => {
		const servicesStats = servicesStatsQuery.data;
		if (!servicesStats || servicesStats.length === 0) return;

		const aggregated: AggregatedStats = {
			cpuPercentage: 0,
			memoryUsage: 0,
			memoryLimit: 0,
			memoryPercentage: 0,
			networkRx: 0,
			networkTx: 0,
			diskRead: 0,
			diskWrite: 0,
			timestamp: new Date()
		};

		servicesStats.forEach((stats: ContainerStats) => {
			aggregated.cpuPercentage += stats.cpuPercentage;
			aggregated.memoryUsage += stats.memoryUsage;
			aggregated.memoryLimit += stats.memoryLimit;
			aggregated.networkRx += stats.networkRx;
			aggregated.networkTx += stats.networkTx;
			aggregated.diskRead += stats.diskRead;
			aggregated.diskWrite += stats.diskWrite;
		});

		// Calculate average memory percentage
		if (aggregated.memoryLimit > 0) {
			aggregated.memoryPercentage = (aggregated.memoryUsage / aggregated.memoryLimit) * 100;
		}

		// Calculate rates (bytes per second) based on difference from previous stats
		let newRates: RateStats | null = null;
		if (previousStatsRef) {
			const timeDiff = (aggregated.timestamp.getTime() - previousStatsRef.timestamp.getTime()) / 1000;
			if (timeDiff > 0) {
				newRates = {
					networkRxRate: Math.max(0, (aggregated.networkRx - previousStatsRef.networkRx) / timeDiff),
					networkTxRate: Math.max(0, (aggregated.networkTx - previousStatsRef.networkTx) / timeDiff),
					diskReadRate: Math.max(0, (aggregated.diskRead - previousStatsRef.diskRead) / timeDiff),
					diskWriteRate: Math.max(0, (aggregated.diskWrite - previousStatsRef.diskWrite) / timeDiff),
					timestamp: aggregated.timestamp
				};
			}
		}

		previousStatsRef = aggregated;

		// Update history - use untrack to avoid creating dependencies on history arrays
		const fiveMinutesAgo = new Date(Date.now() - 5 * 60 * 1000);

		untrack(() => {
			statsHistory = [...statsHistory, aggregated].filter((stat) => stat.timestamp >= fiveMinutesAgo);

			if (newRates) {
				rateHistory = [...rateHistory, newRates].filter((stat) => stat.timestamp >= fiveMinutesAgo);
			}
		});

		currentRates = newRates;
		currentStats = aggregated;
	});

	// Reset history when services stop
	$effect(() => {
		if (!isActive) {
			untrack(() => {
				statsHistory = [];
				rateHistory = [];
				previousStatsRef = null;
				currentStats = null;
				currentRates = null;
			});
		}
	});

	// Use utility functions to get best units based on data
	const memoryUnit = $derived(getBestMemoryUnit(statsHistory, (s) => s.memoryUsage));
	const networkUnit = $derived(getBestNetworkUnit(statsHistory, (s) => Math.max(s.networkRx, s.networkTx)));
	const networkRateUnit = $derived(getBestNetworkRateUnit(rateHistory, (s) => Math.max(s.networkRxRate, s.networkTxRate)));
	const diskUnit = $derived(getBestDiskUnit(statsHistory, (s) => Math.max(s.diskRead, s.diskWrite)));
	const diskRateUnit = $derived(getBestDiskRateUnit(rateHistory, (s) => Math.max(s.diskReadRate, s.diskWriteRate)));

	// Prepare chart data
	const cpuChartData = $derived(
		statsHistory.map((stat) => ({
			timestamp: stat.timestamp,
			cpu: stat.cpuPercentage
		}))
	);

	const memoryChartData = $derived(
		statsHistory.map((stat) => ({
			timestamp: stat.timestamp,
			memory: stat.memoryUsage / memoryUnit.divisor
		}))
	);

	const networkChartData = $derived(
		rateHistory.map((stat) => ({
			timestamp: stat.timestamp,
			rx: stat.networkRxRate / networkRateUnit.divisor,
			tx: stat.networkTxRate / networkRateUnit.divisor
		}))
	);

	const diskChartData = $derived(
		rateHistory.map((stat) => ({
			timestamp: stat.timestamp,
			read: stat.diskReadRate / diskRateUnit.divisor,
			write: stat.diskWriteRate / diskRateUnit.divisor
		}))
	);
</script>

{#if !isActive}
	<div
		class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg p-6"
	>
		<div class="flex items-center gap-2 mb-4">
			<Activity class="h-5 w-5 text-gray-600 dark:text-gray-400" />
			<h3 class="text-lg font-semibold text-gray-900 dark:text-white">
				{$t('common.projectStatistics')}
			</h3>
		</div>
		<p class="text-sm text-gray-600 dark:text-gray-400">{$t('common.noRunningServices')}</p>
	</div>
{:else}
	<div
		class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg hover:shadow-2xl transition-all duration-300 overflow-hidden"
	>
		<!-- Header -->
		<div class="px-6 py-4 border-b border-gray-200 dark:border-gray-700">
			<div class="flex items-center gap-2">
				<Activity class="h-5 w-5 text-gray-600 dark:text-gray-400" />
				<h3 class="text-lg font-semibold text-gray-900 dark:text-white">Project Statistics</h3>
			</div>
		</div>

		<!-- Stats Content -->
		<div class="p-6 space-y-6">
			<!-- CPU Usage -->
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-2">
						<Cpu class="h-4 w-4 text-blue-600 dark:text-blue-400" />
						<span class="text-sm font-semibold text-gray-900 dark:text-white">CPU Usage</span>
					</div>
					{#if currentStats}
						<span class="text-sm font-mono text-blue-600 dark:text-blue-400">
							{currentStats.cpuPercentage.toFixed(2)}%
						</span>
					{/if}
				</div>
				<LineChart
					data={cpuChartData}
					lines={[{ key: 'cpu', label: 'CPU %', color: '#3b82f6' }]}
					height={150}
					formatValue={(v) => `${v.toFixed(1)}%`}
				/>
			</div>

			<!-- Memory Usage -->
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-2">
						<HardDrive class="h-4 w-4 text-green-600 dark:text-green-400" />
						<span class="text-sm font-semibold text-gray-900 dark:text-white">Memory</span>
					</div>
					{#if currentStats}
						<span class="text-sm font-mono text-green-600 dark:text-green-400">
							{formatBytes(currentStats.memoryUsage)} / {formatBytes(currentStats.memoryLimit)}
						</span>
					{/if}
				</div>
				<LineChart
					data={memoryChartData}
					lines={[{ key: 'memory', label: `Memory (${memoryUnit.unit})`, color: '#10b981' }]}
					height={150}
					formatValue={(v) => `${v.toFixed(2)} ${memoryUnit.unit}`}
				/>
			</div>

			<!-- Network Usage -->
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-2">
						<svg
							class="h-4 w-4 text-purple-600 dark:text-purple-400"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
							/>
						</svg>
						<span class="text-sm font-semibold text-gray-900 dark:text-white"
							>Network (RX / TX)</span
						>
					</div>
					{#if currentStats}
						<div class="text-right">
							<span class="text-sm font-mono text-purple-600 dark:text-purple-400">
								{formatBytes(currentStats.networkRx)} / {formatBytes(currentStats.networkTx)}
							</span>
							{#if currentRates}
								<div class="text-xs font-mono text-gray-500 dark:text-gray-400">
									{formatBytes(currentRates.networkRxRate)}/s / {formatBytes(currentRates.networkTxRate)}/s
								</div>
							{/if}
						</div>
					{/if}
				</div>
				<LineChart
					data={networkChartData}
					lines={[
						{ key: 'rx', label: `RX (${networkRateUnit.unit})`, color: '#8b5cf6' },
						{ key: 'tx', label: `TX (${networkRateUnit.unit})`, color: '#f59e0b' }
					]}
					height={150}
					formatValue={(v) => `${v.toFixed(2)} ${networkRateUnit.unit}`}
				/>
			</div>

			<!-- Disk I/O -->
			<div class="space-y-3">
				<div class="flex items-center justify-between">
					<div class="flex items-center gap-2">
						<HardDrive class="h-4 w-4 text-pink-600 dark:text-pink-400" />
						<span class="text-sm font-semibold text-gray-900 dark:text-white"
							>Disk IO (Read / Write)</span
						>
					</div>
					{#if currentStats}
						<div class="text-right">
							<span class="text-sm font-mono text-pink-600 dark:text-pink-400">
								{formatBytes(currentStats.diskRead)} / {formatBytes(currentStats.diskWrite)}
							</span>
							{#if currentRates}
								<div class="text-xs font-mono text-gray-500 dark:text-gray-400">
									{formatBytes(currentRates.diskReadRate)}/s / {formatBytes(currentRates.diskWriteRate)}/s
								</div>
							{/if}
						</div>
					{/if}
				</div>
				<LineChart
					data={diskChartData}
					lines={[
						{ key: 'read', label: `Read (${diskRateUnit.unit})`, color: '#8b5cf6' },
						{ key: 'write', label: `Write (${diskRateUnit.unit})`, color: '#ec4899' }
					]}
					height={150}
					formatValue={(v) => `${v.toFixed(2)} ${diskRateUnit.unit}`}
				/>
			</div>
		</div>
	</div>
{/if}
