// docker-compose-manager-front-new/src/lib/components/compose/ProjectInfoSection.svelte
<script lang="ts">
	import { createQuery } from '@tanstack/svelte-query';
	import { goto } from '$app/navigation';
	import { composeApi } from '$lib/api';
	import { Edit, Network, HardDrive, Tag, Variable } from 'lucide-svelte';
	import { t } from '$lib/i18n';
	import type { ServiceDetails, NetworkDetails, VolumeDetails } from '$lib/types';

	interface Props {
		projectName: string;
		projectPath?: string;
	}

	let { projectName, projectPath }: Props = $props();

	const parsedDetailsQuery = createQuery(() => ({
		queryKey: ['projectParsedDetails', projectName],
		queryFn: () => composeApi.getProjectParsedDetails(projectName)
	}));

	async function handleEditFile() {
		if (!projectPath) return;
		try {
			const fileContent = await composeApi.getFileByPath(projectPath);
			goto(`/compose/files/${fileContent.id}/edit`);
		} catch (e) {
			console.error('Failed to get file ID:', e);
		}
	}

</script>

{#if parsedDetailsQuery.isLoading}
	<div
		class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg p-6"
	>
		<h3 class="text-lg font-semibold text-gray-900 dark:text-white">Compose File Details</h3>
		<p class="text-sm text-gray-600 dark:text-gray-400 mt-2">Loading...</p>
	</div>
{:else if parsedDetailsQuery.error || !parsedDetailsQuery.data}
	<div
		class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg p-6"
	>
		<h3 class="text-lg font-semibold text-gray-900 dark:text-white">Compose File Details</h3>
		<p class="text-sm text-gray-600 dark:text-gray-400 mt-2">No details available</p>
	</div>
{:else}
	{@const parsedDetails = parsedDetailsQuery.data}
	<div
		class="bg-white dark:bg-gray-800 rounded-2xl border border-gray-200 dark:border-gray-700 shadow-lg hover:shadow-2xl transition-all duration-300 overflow-hidden"
	>
		<div
			class="px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between"
		>
			<h3 class="text-lg font-semibold text-gray-900 dark:text-white flex items-center gap-2">
				Compose File Details
			</h3>
			{#if projectPath}
				<button
					onclick={handleEditFile}
					class="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors"
				>
					<Edit class="h-4 w-4" />
					Edit File
				</button>
			{/if}
		</div>

		<div class="p-6 space-y-4">
			<!-- Services Section -->
			{#if parsedDetails.services && Object.keys(parsedDetails.services).length > 0}
				<div class="space-y-3">
					<div class="flex items-center gap-2 text-gray-900 dark:text-white font-semibold">
						<Tag class="h-4 w-4 text-blue-600 dark:text-blue-400" />
						<span>Services ({Object.keys(parsedDetails.services).length})</span>
					</div>
					{#each Object.entries(parsedDetails.services) as [serviceName, service]}
						{@const typedService = service as ServiceDetails}
						<div
							class="border border-gray-200 dark:border-gray-700 rounded-lg p-4 space-y-3 bg-gray-50 dark:bg-gray-900/50"
						>
							<div class="flex items-center justify-between">
								<h4 class="font-semibold text-sm text-gray-900 dark:text-white">{serviceName}</h4>
								{#if typedService.image}
									<span
										class="text-xs text-gray-600 dark:text-gray-400 font-mono bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded"
									>
										{typedService.image}
									</span>
								{/if}
							</div>

							{#if typedService.environment && Object.keys(typedService.environment).length > 0}
								<div class="space-y-1">
									<div class="flex items-center gap-1 text-xs text-gray-600 dark:text-gray-400">
										<Variable class="h-3 w-3" />
										<span>{$t('common.environmentVariables')}</span>
									</div>
									<div
										class="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-32 overflow-y-auto"
									>
										{#each Object.entries(typedService.environment) as [key, value]}
											<div class="flex gap-2">
												<span class="text-blue-600 dark:text-blue-400 font-semibold">{key}:</span>
												<span class="text-gray-700 dark:text-gray-300 break-all"
													>{value || '""'}</span
												>
											</div>
										{/each}
									</div>
								</div>
							{/if}

							{#if typedService.ports && typedService.ports.length > 0}
								<div class="space-y-1">
									<div class="text-xs text-gray-600 dark:text-gray-400">
										{$t('containers.ports')}
									</div>
									<div class="flex flex-wrap gap-1">
										{#each typedService.ports as port}
											<span
												class="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono"
											>
												{port}
											</span>
										{/each}
									</div>
								</div>
							{/if}

							{#if typedService.volumes && typedService.volumes.length > 0}
								<div class="space-y-1">
									<div class="text-xs text-gray-600 dark:text-gray-400">
										{$t('containers.volumes')}
									</div>
									<div
										class="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-24 overflow-y-auto"
									>
										{#each typedService.volumes as volume}
											<div class="text-gray-700 dark:text-gray-300">{volume}</div>
										{/each}
									</div>
								</div>
							{/if}

							{#if typedService.labels && Object.keys(typedService.labels).length > 0}
								<div class="space-y-1">
									<div class="text-xs text-gray-600 dark:text-gray-400">
										{$t('containers.labels')}
									</div>
									<div
										class="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-24 overflow-y-auto"
									>
										{#each Object.entries(typedService.labels) as [key, value]}
											<div class="flex gap-2">
												<span class="text-blue-600 dark:text-blue-400">{key}:</span>
												<span class="text-gray-700 dark:text-gray-300">{value}</span>
											</div>
										{/each}
									</div>
								</div>
							{/if}

							<div class="flex flex-wrap gap-2 text-xs">
								{#if typedService.restart}
									<span
										class="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 px-2 py-1 rounded"
									>
										restart: {typedService.restart}
									</span>
								{/if}
								{#if typedService.dependsOn && typedService.dependsOn.length > 0}
									<span
										class="bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-2 py-1 rounded"
									>
										depends on: {typedService.dependsOn.join(', ')}
									</span>
								{/if}
							</div>
						</div>
					{/each}
				</div>
			{/if}

			<!-- Networks Section -->
			{#if parsedDetails.networks && Object.keys(parsedDetails.networks).length > 0}
				<div class="space-y-2">
					<div class="flex items-center gap-2 text-gray-900 dark:text-white font-semibold">
						<Network class="h-4 w-4 text-green-600 dark:text-green-400" />
						<span>Networks ({Object.keys(parsedDetails.networks).length})</span>
					</div>
					{#each Object.entries(parsedDetails.networks) as [networkName, network]}
						{@const typedNetwork = network as NetworkDetails}
						<div
							class="border border-gray-200 dark:border-gray-700 rounded-lg p-3 space-y-2 bg-gray-50 dark:bg-gray-900/50"
						>
							<div class="flex items-center justify-between">
								<h4 class="font-semibold text-sm text-gray-900 dark:text-white">{networkName}</h4>
								{#if typedNetwork.driver}
									<span
										class="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono"
									>
										driver: {typedNetwork.driver}
									</span>
								{/if}
							</div>
							{#if typedNetwork.external}
								<span
									class="text-xs bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300 px-2 py-1 rounded inline-block"
								>
									external
								</span>
							{/if}
						</div>
					{/each}
				</div>
			{/if}

			<!-- Volumes Section -->
			{#if parsedDetails.volumes && Object.keys(parsedDetails.volumes).length > 0}
				<div class="space-y-2">
					<div class="flex items-center gap-2 text-gray-900 dark:text-white font-semibold">
						<HardDrive class="h-4 w-4 text-orange-600 dark:text-orange-400" />
						<span>Volumes ({Object.keys(parsedDetails.volumes).length})</span>
					</div>
					{#each Object.entries(parsedDetails.volumes) as [volumeName, volume]}
						{@const typedVolume = volume as VolumeDetails}
						<div
							class="border border-gray-200 dark:border-gray-700 rounded-lg p-3 space-y-2 bg-gray-50 dark:bg-gray-900/50"
						>
							<div class="flex items-center justify-between">
								<h4 class="font-semibold text-sm text-gray-900 dark:text-white">{volumeName}</h4>
								{#if typedVolume.driver}
									<span
										class="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono"
									>
										driver: {typedVolume.driver}
									</span>
								{/if}
							</div>
							{#if typedVolume.external}
								<span
									class="text-xs bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300 px-2 py-1 rounded inline-block"
								>
									external
								</span>
							{/if}
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
{/if}

// docker-compose-manager-front/src/components/compose/ProjectInfoSection.tsx
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { composeApi } from '@/api/compose';
import { Edit, Network, HardDrive, Tag, Variable } from 'lucide-react';
import type { ServiceDetails, NetworkDetails, VolumeDetails } from '@/types/compose';
import { InfoCard, type InfoSection } from '@/components/common/InfoCard';
import { t } from '@/i18n';

interface ProjectInfoSectionProps {
  projectName: string;
  projectPath?: string;
}

export function ProjectInfoSection({ projectName, projectPath }: ProjectInfoSectionProps) {
  const navigate = useNavigate();
  const { data: parsedDetails, isLoading, error } = useQuery({
    queryKey: ['projectParsedDetails', projectName],
    queryFn: () => composeApi.getProjectParsedDetails(projectName),
  });

  const handleEditFile = async () => {
    if (!projectPath) return;
    try {
      const fileContent = await composeApi.getFileByPath(projectPath);
      navigate(`/compose/files/${fileContent.id}/edit`);
    } catch (e) {
      console.error('Failed to get file ID:', e);
    }
  };

  if (isLoading) {
    return <InfoCard title="Compose File Details" sections={[]} />;
  }
  if (error || !parsedDetails) {
    return <InfoCard title="Compose File Details" sections={[]} />;
  }

  // Build sections array
  const sections: InfoSection[] = [];

  // Services section
  if (parsedDetails.services && Object.keys(parsedDetails.services).length > 0) {
    sections.push({
      id: 'services',
      title: `Services`,
      icon: <Tag className="h-4 w-4 text-blue-600 dark:text-blue-400" />,
      count: Object.keys(parsedDetails.services).length,
      initiallyOpen: true,
      content: (
        <div className="space-y-3">
          {Object.entries(parsedDetails.services).map(([serviceName, service]: [string, ServiceDetails]) => (
            <div key={serviceName} className="border border-gray-200 dark:border-gray-700 rounded-lg p-4 space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="font-semibold text-sm text-gray-900 dark:text-white">{serviceName}</h4>
                {service.image && (
                  <span className="text-xs text-gray-600 dark:text-gray-400 font-mono bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded">
                    {service.image}
                  </span>
                )}
              </div>
              {service.environment && Object.keys(service.environment).length > 0 && (
                <div className="space-y-1">
                  <div className="flex items-center gap-1 text-xs text-gray-600 dark:text-gray-400">
                    <Variable className="h-3 w-3" />
                    <span>{t('common.environmentVariables')}</span>
                  </div>
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-32 overflow-y-auto">
                    {Object.entries(service.environment).map(([key, value]) => (
                      <div key={key} className="flex gap-2">
                        <span className="text-blue-600 dark:text-blue-400 font-semibold">{key}:</span>
                        <span className="text-gray-700 dark:text-gray-300 break-all">{value as string || '""'}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              {service.ports && service.ports.length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs text-gray-600 dark:text-gray-400">{t('containers.ports')}</div>
                  <div className="flex flex-wrap gap-1">
                    {service.ports.map((port: string, idx: number) => (
                      <span key={idx} className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono">
                        {port}
                      </span>
                    ))}
                  </div>
                </div>
              )}
              {service.volumes && service.volumes.length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs text-gray-600 dark:text-gray-400">{t('containers.volumes')}</div>
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-24 overflow-y-auto">
                    {service.volumes.map((volume: string, idx: number) => (
                      <div key={idx} className="text-gray-700 dark:text-gray-300">{volume}</div>
                    ))}
                  </div>
                </div>
              )}
              {service.labels && Object.keys(service.labels).length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs text-gray-600 dark:text-gray-400">{t('containers.labels')}</div>
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1 max-h-24 overflow-y-auto">
                    {Object.entries(service.labels).map(([key, value]) => (
                      <div key={key} className="flex gap-2">
                        <span className="text-blue-600 dark:text-blue-400">{key}:</span>
                        <span className="text-gray-700 dark:text-gray-300">{value as string}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
              <div className="flex flex-wrap gap-2 text-xs">
                {service.restart && (
                  <span className="bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 px-2 py-1 rounded">
                    restart: {service.restart}
                  </span>
                )}
                {service.dependsOn && service.dependsOn.length > 0 && (
                  <span className="bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 px-2 py-1 rounded">
                    depends on: {service.dependsOn.join(', ')}
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      ),
    });
  }

  if (parsedDetails.networks && Object.keys(parsedDetails.networks).length > 0) {
    sections.push({
      id: 'networks',
      title: 'Networks',
      icon: <Network className="h-4 w-4 text-green-600 dark:text-green-400" />,
      count: Object.keys(parsedDetails.networks).length,
      content: (
        <div className="space-y-2">
          {Object.entries(parsedDetails.networks).map(([networkName, network]: [string, NetworkDetails]) => (
            <div key={networkName} className="border border-gray-200 dark:border-gray-700 rounded-lg p-3 space-y-2">
              <div className="flex items-center justify-between">
                <h4 className="font-semibold text-sm text-gray-900 dark:text-white">{networkName}</h4>
                {network.driver && (
                  <span className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono">
                    driver: {network.driver}
                  </span>
                )}
              </div>
              {network.external && (
                <span className="text-xs bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300 px-2 py-1 rounded inline-block">
                  external
                </span>
              )}
              {network.labels && Object.keys(network.labels).length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs text-gray-600 dark:text-gray-400">Labels</div>
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1">
                    {Object.entries(network.labels).map(([key, value]) => (
                      <div key={key} className="text-gray-700 dark:text-gray-300">
                        {key}: {value as string}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      ),
    });
  }

  if (parsedDetails.volumes && Object.keys(parsedDetails.volumes).length > 0) {
    sections.push({
      id: 'volumes',
      title: 'Volumes',
      icon: <HardDrive className="h-4 w-4 text-orange-600 dark:text-orange-400" />,
      count: Object.keys(parsedDetails.volumes).length,
      content: (
        <div className="space-y-2">
          {Object.entries(parsedDetails.volumes).map(([volumeName, volume]: [string, VolumeDetails]) => (
            <div key={volumeName} className="border border-gray-200 dark:border-gray-700 rounded-lg p-3 space-y-2">
              <div className="flex items-center justify-between">
                <h4 className="font-semibold text-sm text-gray-900 dark:text-white">{volumeName}</h4>
                {volume.driver && (
                  <span className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 px-2 py-1 rounded font-mono">
                    driver: {volume.driver}
                  </span>
                )}
              </div>
              {volume.external && (
                <span className="text-xs bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-300 px-2 py-1 rounded inline-block">
                  external
                </span>
              )}
              {volume.labels && Object.keys(volume.labels).length > 0 && (
                <div className="space-y-1">
                  <div className="text-xs text-gray-600 dark:text-gray-400">Labels</div>
                  <div className="bg-gray-50 dark:bg-gray-900/50 rounded p-2 text-xs font-mono space-y-1">
                    {Object.entries(volume.labels).map(([key, value]) => (
                      <div key={key} className="text-gray-700 dark:text-gray-300">
                        {key}: {value as string}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      ),
    });
  }

  return (
    <InfoCard
      title="Compose File Details"
      sections={sections}
      headerActions={projectPath && (
        <button
          onClick={handleEditFile}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors"
        >
          <Edit className="h-4 w-4" />
          Edit File
        </button>
      )}
    />
  );
}
