// docker-compose-manager-front/src/components/layout/MainLayout.tsx
import { useState } from 'react';
import type { ReactNode } from 'react';
import { Sidebar } from './Sidebar';
import { Header } from './Header';

interface MainLayoutProps {
  children: ReactNode;
}

export const MainLayout = ({ children }: MainLayoutProps) => {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <div className="flex h-screen bg-gray-100 dark:bg-gray-900 transition-colors">
      <Sidebar isOpen={isSidebarOpen} onToggle={toggleSidebar} />

  <div className="flex flex-col flex-1 overflow-hidden">
        <Header onToggleSidebar={toggleSidebar} />

        <main className="flex-1 overflow-y-auto p-8 lg:p-10 bg-gray-50 dark:bg-gray-900">
          <div className="mx-auto">
            {children}
          </div>
        </main>
      </div>
    </div>
  );
};

// docker-compose-manager-front-new/src/lib/components/layout/MainLayout.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import Sidebar from './Sidebar.svelte';
  import Header from './Header.svelte';

  interface Props {
    children: Snippet;
  }

  let { children }: Props = $props();
  let isSidebarOpen = $state(true);

  function toggleSidebar() {
    isSidebarOpen = !isSidebarOpen;
  }
</script>

<div class="flex h-screen bg-gray-100 dark:bg-gray-900 transition-colors">
  <Sidebar isOpen={isSidebarOpen} />

  <div class="flex flex-col flex-1 overflow-hidden">
    <Header onToggleSidebar={toggleSidebar} />

    <main class="flex-1 overflow-y-auto p-8 lg:p-10 bg-gray-50 dark:bg-gray-900">
      <div class="mx-auto">
        {@render children()}
      </div>
    </main>
  </div>
</div>
