// docker-compose-manager-front/src/components/ui/badge.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const badgeVariants = cva(
  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground hover:bg-primary/80",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80",
        destructive:
          "border-transparent bg-destructive text-destructive-foreground hover:bg-destructive/80",
        outline: "text-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  }
)

export interface BadgeProps
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge({ className, variant, ...props }: BadgeProps) {
  return (
    <div className={cn(badgeVariants({ variant }), className)} {...props} />
  )
}
/* eslint-disable react-refresh/only-export-components */

export { Badge }
export { badgeVariants }

// docker-compose-manager-front-new/src/lib/components/ui/badge.svelte
<script lang="ts">
  import { cn } from '$lib/utils';
  import type { Snippet } from 'svelte';
  import type { HTMLAttributes } from 'svelte/elements';

  type Variant = 'default' | 'secondary' | 'destructive' | 'outline' | 'success' | 'warning';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    variant?: Variant;
    children?: Snippet;
    class?: string;
  }

  let { variant = 'default', children, class: className, ...restProps }: Props = $props();

  const variantClasses: Record<Variant, string> = {
    default: 'bg-primary text-white',
    secondary: 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100',
    destructive: 'bg-danger text-white',
    outline: 'border border-gray-300 dark:border-gray-600 text-gray-900 dark:text-gray-100',
    success: 'bg-success text-white',
    warning: 'bg-warning text-white',
  };
</script>

<div
  class={cn(
    'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold transition-colors',
    variantClasses[variant],
    className
  )}
  {...restProps}
>
  {#if children}
    {@render children()}
  {/if}
</div>
