// docker-compose-manager-front-new/src/lib/components/common/ActivityItem.svelte
<script lang="ts">
  import { CheckCircle, XCircle, User, Package, Container, FileText } from 'lucide-svelte';
  import { formatDistanceToNow } from 'date-fns';
  import { enUS, fr, es } from 'date-fns/locale';
  import { t, locale as localeStore } from '$lib/i18n';
  import type { Activity } from '$lib/api/dashboard';
  import { get } from 'svelte/store';

  interface Props {
    item: Activity;
  }

  let { item }: Props = $props();

  const iconMap: Record<string, typeof User> = {
    User,
    ComposeProject: Package,
    Container,
    ComposeFile: FileText
  };

  const localeMap: Record<string, typeof enUS> = { en: enUS, fr, es };

  const resourceIcon = $derived(iconMap[item.resourceType] || null);
  const currentLocaleCode = $derived(get(localeStore));
  const currentLocale = $derived(localeMap[currentLocaleCode] || enUS);
  const timeAgo = $derived(formatDistanceToNow(new Date(item.timestamp), {
    addSuffix: true,
    locale: currentLocale
  }));
</script>

<div class="flex items-start gap-4 p-6 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors">
  <div class="flex-shrink-0 p-3 rounded-full {item.success ? 'bg-green-100 dark:bg-green-900/30' : 'bg-red-100 dark:bg-red-900/30'}">
    {#if item.success}
      <CheckCircle class="w-5 h-5 text-green-600 dark:text-green-400" />
    {:else}
      <XCircle class="w-5 h-5 text-red-600 dark:text-red-400" />
    {/if}
  </div>
  <div class="flex-1 min-w-0">
    <p class="text-sm font-medium text-gray-800 dark:text-gray-100">
      <span class="font-semibold">{item.username}</span>
      <span class="text-gray-600 dark:text-gray-400">
        {t('common.performedAction', { action: item.action })}
      </span>
      {#if item.resourceType}
        <span class="text-gray-600 dark:text-gray-400">
          {t('common.onResource', { type: item.resourceType })}
        </span>
        {#if item.resourceId}
          <span class="font-mono text-blue-600 dark:text-blue-400">
            {item.resourceId}
          </span>
        {/if}
      {/if}
    </p>
    {#if item.details}
      <p class="text-xs text-gray-500 dark:text-gray-500 mt-1 truncate">
        {item.details}
      </p>
    {/if}
    <p class="text-xs text-gray-400 dark:text-gray-600 mt-1">
      {timeAgo}
    </p>
  </div>
  {#if resourceIcon}
    {@const IconComponent = resourceIcon}
    <div class="flex-shrink-0 text-gray-400 dark:text-gray-600">
      <IconComponent class="w-5 h-5" />
    </div>
  {/if}
</div>

// docker-compose-manager-front/src/components/common/ActivityItem.tsx
import React from 'react';
import { CheckCircle, AlertCircle } from 'lucide-react';

interface ActivityItemProps {
  item: {
    id: number;
    username: string;
    action: string;
    resourceType: string;
    details: string;
    timestamp: string;
    success: boolean;
  };
}


const ActivityItemComponent = ({ item }: ActivityItemProps) => (
  <div className="p-5 hover:bg-white dark:hover:bg-gray-800 transition-all duration-200 group">
    <div className="flex items-start gap-4">
      <div className={`p-2 rounded-lg ${item.success ? 'bg-green-100 dark:bg-green-900/30' : 'bg-red-100 dark:bg-red-900/30'}`}>
        {item.success ? (
          <CheckCircle className="w-5 h-5 text-green-600 dark:text-green-400" />
        ) : (
          <AlertCircle className="w-5 h-5 text-red-600 dark:text-red-400" />
        )}
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1">
          <p className="text-sm font-semibold text-gray-900 dark:text-white">
            {item.username}
          </p>
          <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 font-medium">
            {item.resourceType}
          </span>
        </div>
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">
          <span className="font-medium text-gray-700 dark:text-gray-300">{item.action}</span> - {item.details}
        </p>
        <p className="text-xs text-gray-500 dark:text-gray-500">
          {new Date(item.timestamp).toLocaleString()}
        </p>
      </div>
    </div>
  </div>
);

export const ActivityItem = React.memo(ActivityItemComponent);
