// docker-compose-manager-front-new/src/lib/components/common/LoadingState.svelte
<script lang="ts">
  import { Loader2 } from 'lucide-svelte';
  import { t } from '$lib/i18n';

  interface Props {
    message?: string;
  }

  let { message = t('common.loading') }: Props = $props();
</script>

<div class="flex flex-col items-center justify-center py-12" role="status" aria-live="polite">
  <Loader2 class="w-8 h-8 animate-spin text-blue-600" aria-hidden="true" />
  <p class="mt-3 text-sm text-gray-600 dark:text-gray-400">{message}</p>
</div>

// docker-compose-manager-front/src/components/common/LoadingState.tsx
import { t } from '../../i18n';

export const LoadingState = ({ message = t('common.loading') }: { message?: string }) => (
  <div className="p-8 text-center" role="status" aria-live="polite">
    <div className="inline-block animate-spin rounded-full h-8 w-8 border-4 border-gray-300 dark:border-gray-600 border-t-blue-600" aria-hidden="true"></div>
    <p className="text-gray-600 dark:text-gray-400 mt-3">{message}</p>
  </div>
);
