// docker-compose-manager-front-new/src/lib/components/common/ThemeToggle.svelte
<script lang="ts">
  import { Sun, Moon } from 'lucide-svelte';
  import * as theme from '$lib/stores/theme.svelte';

  interface Props {
    class?: string;
  }

  let { class: className = '' }: Props = $props();
</script>

<button
  onclick={() => theme.toggle()}
  class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors {className}"
  aria-label="Toggle theme"
>
  {#if theme.isDark.current}
    <Sun class="w-5 h-5 text-gray-600 dark:text-gray-400" />
  {:else}
    <Moon class="w-5 h-5 text-gray-600 dark:text-gray-400" />
  {/if}
</button>

// docker-compose-manager-front/src/components/common/ThemeToggle.tsx
import { Moon, Sun } from 'lucide-react';
import { useTheme } from '../../hooks/useTheme';

export const ThemeToggle = () => {
  const { theme, toggleTheme } = useTheme();

  return (
    <button
      onClick={toggleTheme}
      className="p-2 rounded-md hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
      aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`}
      title={`Switch to ${theme === 'light' ? 'dark' : 'light'} mode`}
    >
      {theme === 'light' ? (
        <Moon className="w-5 h-5 text-gray-600 dark:text-gray-300" />
      ) : (
        <Sun className="w-5 h-5 text-gray-300" />
      )}
    </button>
  );
};
